services:
  db:
    container_name: trivia-db
    image: postgres:14.1
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: trivia-app
    image: api
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    environment:
      FLASK_APP: flaskr.py
      FLASK_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  admin:
    container_name: trivia-admin
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    container_name: trivia-frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      target: development
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
volumes:
  db:
  app:
